function [ exx_filt,exy_filt,eyx_filt,eyy_filt,gxy_filt,gtorsion_filt ] = ...
    filterStrain( exx,exy,eyx,eyy,gxy,gtorsion,filterstruct,obj_handle )
% Function for performing revised filtering of the strain field in 
% FourDSTEM_Analysis_Engine.m. Takes a struct generated by
% buildFilterStruct.m as input.
%
% Nathanael Kazmierczak, 05/19/2020

end

